create table public.trades (
  id text primary key,
  "orderId" text,
  symbol text,
  side text,
  quantity numeric,
  price numeric,
  timestamp bigint,
  status text default 'OPEN',
  commission numeric,
  "commissionAsset" text,
  "stopLossPrice" numeric,
  "takeProfitPrice" numeric,
  "exitPrice" numeric,
  "exitTimestamp" bigint,
  "exitReason" text,  -- Reason for closing the trade (e.g., STOP_LOSS, TAKE_PROFIT, TRAILING_STOP_LOSS, STRATEGY_EXIT)
  "strategyName" text,  -- Name of the strategy that opened this trade
  leverage numeric,
  margin numeric,
  duration bigint,
  -- Trailing Stop Loss fields
  "trailingStopEnabled" boolean,
  "trailingStopActivated" boolean,
  "trailingStopActivationPercent" numeric,
  "trailingStopTrailPercent" numeric,
  "trailingStopHighPrice" numeric,  -- For BUY positions: highest price seen
  "trailingStopLowPrice" numeric,   -- For SELL positions: lowest price seen
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Portfolio Snapshots
create table public.portfolio_snapshots (
  id bigint generated by default as identity primary key,
  timestamp bigint,
  "totalValue" numeric,
  holdings jsonb,
  pnl numeric,
  "pnlPercentage" numeric,
  "winRate" numeric,
  "profitFactor" numeric,
  "winningTrades" integer,
  "losingTrades" integer,
  "openTradesCount" integer,
  "currentEquity" numeric,
  "currentBalance" numeric,
  "walletBalance" numeric,
  "totalMarginUsed" numeric,
  "totalNotionalValue" numeric,
  "initialBalance" numeric,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
create index if not exists idx_portfolio_snapshots_timestamp on public.portfolio_snapshots (timestamp desc);

-- Backtest Results
create table public.backtest_results (
  id bigint generated by default as identity primary key,
  timestamp bigint,
  result jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Application State Persistence
create table public.kv_store (
  key text primary key,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
comment on table public.kv_store is 'Generic key-value store for persisting application state (e.g. risk limits)';
