create table public.trades (
  id text primary key,
  "orderId" text,
  symbol text,
  side text,
  quantity numeric,
  price numeric,
  timestamp bigint,
  status text default 'OPEN',
  commission numeric,
  "commissionAsset" text,
  "stopLossPrice" numeric,
  "takeProfitPrice" numeric,
  "exitPrice" numeric,
  "exitTimestamp" bigint,
  "strategyName" text,  -- Name of the strategy that opened this trade
  duration bigint,
  -- Trailing Stop Loss fields
  "trailingStopEnabled" boolean,
  "trailingStopActivated" boolean,
  "trailingStopActivationPercent" numeric,
  "trailingStopTrailPercent" numeric,
  "trailingStopHighPrice" numeric,  -- For BUY positions: highest price seen
  "trailingStopLowPrice" numeric,   -- For SELL positions: lowest price seen
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Portfolio Snapshots
create table public.portfolio_snapshots (
  id bigint generated by default as identity primary key,
  timestamp bigint,
  "totalValue" numeric,
  holdings jsonb,
  pnl numeric,
  "pnlPercentage" numeric,
  "winRate" numeric,
  "profitFactor" numeric,
  "winningTrades" integer,
  "losingTrades" integer,
  "openTrades" jsonb,
  "closedTrades" jsonb,
  "currentEquity" numeric,
  "currentBalance" numeric,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Backtest Results
create table public.backtest_results (
  id bigint generated by default as identity primary key,
  timestamp bigint,
  result jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
